In [5]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('task1.csv')
df.head()

   Unnamed: 0 Postcode      Borough                           Neighbourhood
0           0      M1B  Scarborough                          Malvern, Rouge
1           1      M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2           2      M1E  Scarborough       Guildwood, Morningside, West Hill
3           3      M1G  Scarborough                                  Woburn
4           4      M1H  Scarborough                               Cedarbrae

In [9]:
pip install geocoder

Collecting geocoder
  Downloading geocoder-1.38.1-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: requests in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from geocoder) (2.23.0)
Collecting ratelim
  Downloading ratelim-0.1.6-py2.py3-none-any.whl (4.0 kB)
Requirement already satisfied: six in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from geocoder) (1.14.0)
Requirement already satisfied: click in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from geocoder) (7.1.2)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Requirement already satisfied: idna<3,>=2.5 in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from requests->geocoder) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from requests->geocoder) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from requests->geocoder) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: decorator in c:\users\pranav\anaconda3\envs\deeplearning\lib\site-packages (from ratelim->geocoder) (4.4.2)
Building wheels for collected packages: future
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491062 sha256=07bb7ae2c280873fd5bcedb0f9fe405802cc7b04acca3d9ff7347998d7c533e0
  Stored in directory: c:\users\pranav\appdata\local\pip\cache\wheels\56\b0\fe\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
Installing collected packages: ratelim, future, geocoder
Successfully installed future-0.18.2 geocoder-1.38.1 ratelim-0.1.6
Note: you may need to restart the kernel to use updated packages.

In [10]:
import geocoder

In [11]:
def get_latlng(postal_code):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Toronto, Ontario'.format(postal_code))
        lat_lng_coords = g.latlng
    return lat_lng_coords
    
get_latlng('M4G')

[43.70941386000004, -79.36309957799995]

In [16]:
postal_codes = df['Postcode']    
coords = [ get_latlng(postal_code) for postal_code in postal_codes.tolist() ]

In [17]:
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df['Latitude'] = df_coords['Latitude']
df['Longitude'] = df_coords['Longitude']
df.head()

,Unnamed: 0,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,0,M1B,Scarborough,"Malvern, Rouge",43.808626,-79.189913
1,1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.785779,-79.157368
2,2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.765806,-79.185284
3,3,M1G,Scarborough,Woburn,43.771545,-79.218135
4,4,M1H,Scarborough,Cedarbrae,43.768791,-79.238813

In [19]:
df[df.Postcode == 'M5G']

,Unnamed: 0,Postcode,Borough,Neighbourhood,Latitude,Longitude
57,57,M5G,Downtown Toronto,Central Bay Street,43.656072,-79.385653

In [20]:
df.to_csv('task2.csv', index=False)

In [21]:
df

,Unnamed: 0,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,0,M1B,Scarborough,"Malvern, Rouge",43.808626,-79.189913
1,1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.785779,-79.157368
2,2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.765806,-79.185284
3,3,M1G,Scarborough,Woburn,43.771545,-79.218135
4,4,M1H,Scarborough,Cedarbrae,43.768791,-79.238813
...,...,...,...,...,...,...
98,98,M9N,York,Weston,43.705496,-79.520370
99,99,M9P,Etobicoke,Westmount,43.696296,-79.533126
100,100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.686887,-79.565507
101,101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.744055,-79.581203
102,102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.711615,-79.588351